# Generated by Django 2.2.7 on 2020-01-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcandidate',
            name='status',
            field=models.CharField(blank=True, default='Pending for invite', max_length=200, null=True),
        ),
    ]
