# Generated by Django 2.2.7 on 2020-01-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0002_createcandidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcandidate',
            name='referralid',
            field=models.CharField(blank=True, default='No-referral', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='createcandidate',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
