# Generated by Django 2.2.7 on 2020-01-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0003_auto_20200106_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcandidate',
            name='candempid',
            field=models.CharField(blank=True, default='Nan', max_length=100, null=True),
        ),
    ]
